### ISSUE TITLE
gpapi.googleplay.RequestError: 'Error while retrieving information from server. DF-DFERH-01'

### ISSUE THREAD

**Issue by ford--prefect** [NoMore201/googleplay-api#113]
When connecting to the play store (via gplaycli) I get the above mentioned error.
Full traceback:

`Traceback (most recent call last):
  File "/usr/bin/gplaycli", line 11, in <module>
    load_entry_point('gplaycli==3.27', 'console_scripts', 'gplaycli')()
  File "/usr/lib/python3.8/site-packages/gplaycli/gplaycli.py", line 623, in main
    cli.prepare_analyse_apks()
  File "/usr/lib/python3.8/site-packages/gplaycli/gplaycli.py", line 475, in prepare_analyse_apks
    to_update = self.analyse_local_apks(list_of_apks, self.download_folder)
  File "/usr/lib/python3.8/site-packages/gplaycli/hooks.py", line 9, in check_connection
    return function(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/gplaycli/gplaycli.py", line 500, in analyse_local_apks
    details = self.api.bulkDetails(package_bunch)
  File "/usr/lib/python3.8/site-packages/gpapi/googleplay.py", line 396, in bulkDetails
    message = self.executeRequestApi2(BULK_URL,
  File "/usr/lib/python3.8/site-packages/gpapi/googleplay.py", line 336, in executeRequestApi2
    raise RequestError(message.commands.displayErrorMessage)
gpapi.googleplay.RequestError: 'Error while retrieving information from server. DF-DFERH-01'
`

**Comment by rehmatworks** [comment]
Maybe you made too many requests using the same GSFID in a short span of time?

**Comment by matlink** [comment]
It is due to #114. Newer version of gplaycli will fix this issue but I'm waiting for the maintainer @NoMore201  to patch and publish a new version.
