### ISSUE TITLE
Error in protobuf on Import

### ISSUE THREAD

**Issue by cstayyab** [NoMore201/googleplay-api#131]
The following line of code:

```python
from gpapi.googleplay import GooglePlayAPI
```
generates this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Development\googleplay-api\gpapi\googleplay.py", line 14, in <module>
    from . import googleplay_pb2, config, utils
  File "D:\Development\googleplay-api\gpapi\googleplay_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

Following the version of related python packages:
```
protobuf==3.11.3
protobuf-compiler==1.0.18
```

**Comment by gurnec** [comment]
It looks like the `protopy` compiler from the `protobuf-compiler` package requires `protobuf` version 3.12.0 or greater. You should probably upgrade `protobuf-compiler` too just to be safe.
