### ISSUE TITLE
An unexpected keyword argument "file" on Python2.7

### ISSUE THREAD

**Issue by electron2008** [NoMore201/googleplay-api#47]
Protobuf version is 3.2.0， i think it should be python version difference. right ?

Error as below:
C:\Users\xxxx\Downloads\googleplay-api-master>python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from gpapi.googleplay import GooglePlayAPI, RequestError
  File "C:\Users\xxxx\Downloads\googleplay-api-master\gpapi\googleplay.py", line 14, in <module>
    from . import googleplay_pb2, config, utils
  File "C:\Users\xxxx\Downloads\googleplay-api-master\gpapi\googleplay_pb2.py", line 41, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'

**Comment by matlink** [comment]
duplicate https://github.com/NoMore201/googleplay-api/issues/34?

**Comment by NoMore201** [comment]
Duplicate of #34
