### ISSUE TITLE
Security Check Error

### ISSUE THREAD

**Issue by matlink** [NoMore201/googleplay-api#67]
Got some security check error recently using newly created accounts:
[INFO] GPlayCli version 3.24 [Python3.6.4] 
[INFO] Configuration file is gplaycli.conf
[INFO] Device is bacon
[INFO] Using credentials to connect to API
[INFO] Using plaintext password
Traceback (most recent call last):
  File "/export/home/valois/.local/share/virtualenvs/gplaycli-b1QJ3HkK/bin/gplaycli", line 11, in <module>
    sys.exit(main())
  File "/export/home/valois/.local/share/virtualenvs/gplaycli-b1QJ3HkK/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 723, in main
    cli.search(args.search_string, nb_results, not args.paid)
  File "/export/home/valois/.local/share/virtualenvs/gplaycli-b1QJ3HkK/lib/python3.6/site-packages/gplaycli/hooks.py", line 8, in check_connection
    self.connect()
  File "/export/home/valois/.local/share/virtualenvs/gplaycli-b1QJ3HkK/lib/python3.6/site-packages/gplaycli/gplaycli.py", line 437, in connect
    gsfId=gsfid)
  File "/export/home/valois/.local/share/virtualenvs/gplaycli-b1QJ3HkK/lib/python3.6/site-packages/gpapi/googleplay.py", line 223, in login
    raise SecurityCheckError()
gpapi.googleplay.SecurityCheckError

Do you know where it could come from?

**Comment by komeilkamal** [comment]
Complete error message is: 
gpapi.googleplay.LoginError: 'Security check is needed, try to visit https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock, or setup an app-specific password' 
You should login in your google account and visit it (https://accounts.google.com/b/0/DisplayUnlockCaptcha).

**Comment by matlink** [comment]
Yeah it seems to work only for the device where I unlocked the security check. It does not work for my travis build :(

**Comment by archon810** [comment]
This is new, I think, and quite annoying. I even have 2FA and application-specific passwords enabled, and it still asks me to go to https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock. Argh, Google.

**Comment by NoMore201** [comment]
Recently this problem intensified, along with random errors. As far as I understand it can be caused by one of those things:

1 - frequent email+passwd logins
2 - frequent public IP change
3 - you are logged in with that account and have an opened session in your browser/android phone

In my case it does not happen in a single testing session from my PC (on the same network), but as pointed out by @matlink travis build fails almost always

**Comment by rehmatworks** [comment]
Point 1 seems to be the cause. This error doesn't come up on Android phones though (even if same account is used on multiple devices). BTW I always re-use the generated token unless it is expired but still my requests were blocked. Looks like Google has set a threshold for the calls to an upper limit that an Android device would normally make and frequent requests may be flagged as the abuse of the service  and it triggers this check.

**Comment by reox** [comment]
I get this error too. I'm logged in with the account on an android device though. 
I can rule out reason number two, as the IP does not change. Reason one might be possible, but as I get this error from the first login attempt on, I doubt it.
Using the token method from my current IP works fine, so at least I know I'm not blacklisted.
I also tried the https://accounts.google.com/b/0/DisplayUnlockCaptcha but this does not help either...

Is the user based login broken right now?

**Comment by reox** [comment]
This is now interesting: On the phone were this account was used, a notification popped up I should investigate the account. It said then further that I was logged out on the phone from the google account and should log in again.
After I entered the password, it said, that suspicious activity was recorded and I have to change my password.

I changed the password and tried again with the changed password to use gplaycli but still get the SecurityCheckError

**Comment by raulperezalejo** [comment]
any update on this? is there any alternative? 
any script for example propose?

**Comment by ouaguid** [comment]
Instead of using your account password (which can generate a validation request via captcha if 2-Step-Verification is enabled), it is preferable to generate and use an App password specific to your application by following the steps mentioned here => [Sign in with App Passwords](https://support.google.com/accounts/answer/185833?hl=en)  (see the section "Create & use App Passwords").

**Comment by Niveshkrishna** [comment]
Did anyone find a work around for this? I'm stuck with same error. I'm using 2FA enabled and have app-specific password.

**Comment by ahm750** [comment]
> Did anyone find a work around for this? I'm stuck with same error. I'm using 2FA enabled and have app-specific password.

Did you find a solution? The same issue is happening to me.

**Comment by Niveshkrishna** [comment]
No, I could not find any solution to this yet. For me some accounts work and some throw captcha error. So it is not entirely clear on why some accounts are failing. Maybe a lot of accounts are created from my IP? 

I will try to explore [this](https://gitlab.com/AuroraOSS/AuroraStore/-/issues/217#note_249390026) approach suggested by @hoffie

**Comment by 89z** [comment]
https://github.com/NoMore201/googleplay-api/issues/84
