### ISSUE TITLE
Item not found, but on GP exist

### ISSUE THREAD

**Issue by imKota** [NoMore201/googleplay-api#78]
https://play.google.com/store/apps/details?id=com.smartdriver.antiradar

```
➜  python3 test/test.py                                                                                                              

Login with ac2dm token and gsfId saved


Getting details for com.smartdriver.antiradar

Traceback (most recent call last):
  File "test/test.py", line 15, in <module>
    details = server.details('com.smartdriver.antiradar')
  File "/usr/local/lib/python3.7/site-packages/gpapi/googleplay.py", line 375, in details
    data = self.executeRequestApi2(path)
  File "/usr/local/lib/python3.7/site-packages/gpapi/googleplay.py", line 336, in executeRequestApi2
    raise RequestError(message.commands.displayErrorMessage)
gpapi.googleplay.RequestError: 'Item not found.'
kota@iMac—Kota ~/Downloads/googleplay-api-next
```

**Comment by Gu1nness** [comment]
Hi !
Excuse me, how did you fix this issue ?
I'm having the same and can't find any way-around.

**Comment by imKota** [comment]
@Gu1nness just try device (Sony Xperia XZ Premium Dual SIM)

**Comment by komeilkamal** [comment]
You should update device vending version, Like below:
```
Vending.version = 81425800
Vending.versionString = 14.2.58-all [0] [PR] 239277684
```

**Comment by Gu1nness** [comment]
Ok, thank you for your answers !
