### ISSUE TITLE
gpapi.googleplay.LoginError: 'server says: BadAuthentication'

### ISSUE THREAD

**Issue by cocozby** [NoMore201/googleplay-api#84]
There seems to be a login error when I use the old version code.
It worked all well when I ran this code several weeks ago.
However, when I logged in with my email and password today, I got the error as in the title.

**Comment by rehmatworks** [comment]
Are you using app specific passwords are regular login details? In most cases, you need to visit https://accounts.google.com/b/0/displayunlockcaptcha and allow access to your account using the same IP address from where you are sending requests using gpapi.

**Comment by oittaa** [comment]
The newest version is also broken on my systems. That captcha trick didn't help.

`gpapi.googleplay.LoginError: 'server says: BadAuthentication'`

**Comment by raulperezalejo** [comment]
@rehmatworks i am using an app specific password, with double factor authentication off, using latest version 0.4.3 and i am getting `server says: BadAuthentication`, i or we may be missing something in the setup that may or may not in the project description. 
If there are other issues raised after this one is because works for other people. 

Thanks

**Comment by theapache64** [comment]
Any  updates on this issue ?

**Comment by danielfrankcom** [comment]
I'm having the same issue. I'm using an app specific password, with 2FA on, and running with the Docker container.

**Comment by EthanArbuckle** [comment]
Try using python3.7.7

**Comment by gkovacs81** [comment]
I was not able to change my python version to 3.7.7, but it works with python 3.7.3 and requests==2.22.0.

**Comment by deeppil** [comment]
Is this still an issue that hasn't been fixed?

**Comment by pnu-s** [comment]
Still having the issue today.

**Comment by 89z** [comment]
Same problem

**Comment by 89z** [comment]
https://github.com/NoMore201/googleplay-api/issues/125
https://github.com/NoMore201/googleplay-api/issues/135
https://github.com/NoMore201/googleplay-api/issues/140

https://github.com/NoMore201/googleplay-api/issues/84

**Comment by 89z** [comment]
I bypassed the error like this:

~~~
pip install urllib3==1.25.11
~~~

but now I get a different error:

~~~
Traceback (most recent call last):
  File "D:\Desktop\googleplay-api-master\play.py", line 7, in <module>
    api.login(email=mail, password=passwd)
  File "D:\Desktop\googleplay-api-master\gpapi\googleplay.py", line 235, in login
    raise SecurityCheckError("Security check is needed, try to visit "
gpapi.googleplay.SecurityCheckError: 'Security check is needed, try to visit
https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock, or setup an
app-specific password'
~~~

**Comment by 89z** [comment]
https://github.com/NoMore201/googleplay-api/issues/67

**Comment by 89z** [comment]
https://github.com/NoMore201/googleplay-api/pull/153

**Comment by 89z** [comment]
I have an alternate tool/module that works:

~~~
PS C:\> googleplay -a com.google.android.youtube
&{DocV2:{Details:{AppDetails:{DeveloperName:Google LLC VersionCode:1524094400
Version:16.43.34 InstallationSize:34674581 UploadDate:Oct 27, 2021}}}}
~~~

https://github.com/89z/googleplay

**Comment by gkovacs81** [comment]
I had again issues but https://github.com/NoMore201/googleplay-api/pull/153 helped.

**Comment by DhruvkumarSeta** [comment]
@gkovacs81 Do we need to log in again or reauthenticate will work? I did try #153  but didn't work
